In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [3]:
from skimage.transform import resize
from skimage.io import imread
target=[]
images=[]
flat_data=[]

In [4]:
dir='/content/drive/MyDrive/data'
categories=['airplane','drones','helicopter']
for i in categories:
  pos=categories.index(i)
  path=os.path.join(dir,i)
  for img in os.listdir(path):
    img_array=imread(os.path.join(path,img)) 
    img_resize=resize(img_array,(150,150,3)) # Nomalization happenes automatically
    flat_data.append(img_resize.flatten())
    images.append(img_resize)
    target.append(pos)
flat_data=np.array(flat_data)
target=np.array(target)
images=np.array(images)
df=pd.DataFrame(flat_data)
df['Target']=target

In [6]:
x=df.iloc[:,1:-1].values
y=df.iloc[:,67500:67501].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0,stratify=y)
y=y.flatten() 
y_train=y_train.flatten() 
y_test=y_test.flatten() 

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn.svm import SVC
svc=SVC()
parameters={'kernel':['rbf','linear'],
            'C': [1,10,100]
}
cv=GridSearchCV(svc,parameters,cv=5)
cv.fit(x_train,y_train)
cv.best_params_

{'C': 10, 'kernel': 'rbf'}

In [14]:
model=SVC(C=10, kernel='rbf')
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)
print(y_test)

[0 0 0 0 2 1 1 0 2 0 1 0 2 1 2 2 2 0 2 2 2 1 2]
[0 1 0 0 2 0 1 0 2 2 1 2 2 1 2 0 2 1 2 0 0 1 1]


In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_pred,y_test)

0.6086956521739131

In [11]:
confusion_matrix(y_pred,y_test)

array([[4, 2, 2],
       [1, 4, 0],
       [3, 1, 6]])

In [12]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.50      0.50      0.50         8\n           1       0.57      0.80      0.67         5\n           2       0.75      0.60      0.67        10\n\n    accuracy                           0.61        23\n   macro avg       0.61      0.63      0.61        23\nweighted avg       0.62      0.61      0.61        23\n'